# Auto-report action script, 3 times a day

name: Auto-report action

on:
  workflow_dispatch
  push:
    branches:
      - master
  schedule:
    - cron: '10 16 * * *'
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        USERNAME: ${{ secrets.Username }}
        PASSWORD: ${{ secrets.Password }}
        CONTNAME: ${{ secrets.Contname }}
        CONTREL: ${{ secrets.Contrel }}
        CONTNUM: ${{ secrets.Contnum }}
      run: |
        python report.py "$USERNAME" "$PASSWORD" --cont_name "$CONTNAME" --cont_rel "$CONTREL" --cont_num "$CONTNUM"
