# Auto-report action script, daily and on demand

name: Auto-report action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '55 15 * * *'



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run report script
        env:
          USERNAME: ${{ secrets.Username }}
          PASSWORD: ${{ secrets.Password }}
          REAL_NAME: ${{ secrets.Real_name }}
          MOBILE_PHONE: ${{ secrets.Mobile_phone }}

        run: |
          python report.py -dsc "$USERNAME" "$PASSWORD"
