# Auto-report action script, 2 times a day and on demand

name: Auto-report action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 14 * * *'
    - cron: '50 15 * * *'
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        USERNAME: ${{ secrets.Username }}
        PASSWORD: ${{ secrets.Password }}
      run: |
        python report.py "$USERNAME" "$PASSWORD"
